package com.ec.conscientia.entities;

import com.badlogic.gdx.scenes.scene2d.ui.Image;

public abstract class Acquirable {

	// item final int IDs
	// Glyphs 1-49
	public final static int EXTRACTION_GLYPH = 1, LUIN_SWORD_GLYPH = 2, LUIN_ARMOR_GLYPH = 3, EIDOS_GLYPH = 4,
			AWARENESS_GLYPH = 5, DISCIPLINE_GLYPH = 6, FARCASTING_GLYPH = 7, OCCULT_GLYPH = 8, RESURRECTION_GLYPH = 9,
			PURIFICATION_GLYPH = 10, DELETION_GLYPH = 11, RESTRICTION_GLYPH = 12, WULFIAS_GLYPH = 13,
			CORRUPTION_GLYPH = 14, NEARCASTER_GLYPH = 15, MAX_GLYPH = 49;
	// Logs 50-99
	public final static int KABU_COMBAT_TOME = 50, KABU_FARCASTER_TOME = 51, KABU_GLYPHS_TOME = 52,
			INTROSPECTION_TOME = 53, CLOCKWORK_CROWS_TOME = 54, KHAA_EXCAVATION_TOME = 55,
			BOOK_OF_QUANGJO_VOL_II_TOME = 56, KABU_RITUAL_TOME = 57, TORMA_III_TOME = 58, TORMA_VII_TOME = 59,
			CONFESSION_OF_THETIAN_TOME = 60, EFFECTS_OF_REDGRAIN_TOME = 61, TONGUES_GLYPH_TOME = 62,
			SONGS_OF_KABU_TOME = 63, VALVORTHR_MANUAL_TOME = 64, KABU_DAZIR_ARCHIVES_TOME = 65,
			KABU_WELLSPRING_QUANGJO_TOME = 66, THE_RED_TOWER = 67, TORMA_VI_TOME = 68, TORMA_X_TOME = 69,
			SANCTUARY_MUNNIN_TOME = 70, KABU_SALT_FOREST_TOME = 71, KABU_RIKHARR_TOME = 72, TORMA_II_TOME = 73,
			KABAN_MYTHS_TOME = 74, DEATHLY_CULTS_TOME = 75, PRECEPTS_OF_THOUGHT_TOME = 76, WHISPERED_PROPHECY_TOME = 77,
			BOOK_OF_QUANGJO_VOL_XVII_TOME = 78, BOOK_OF_QUANGJO_VOL_XX_TOME = 79, ART_AND_ARTIFICE = 80,
			THE_INFINITE_PURSUIT = 81, ORIGINS_OF_THE_SCHISM = 82, PRIMORDIAL_TECHNOCRAFT = 83,
			SPECTRAL_PROJECTION = 84, WAYFARER_EXTRACTIONS = 85, PRIME_ARCHON_LIST = 86, ANALYSIS_OF_RIKHARR = 87, BEFORE_THE_FALL_I = 88, BEFORE_THE_FALL_II = 89, BEFORE_THE_FALL_III = 90,
			MAX_LOG = 99;
	// Mindscape NPCs 100-109
	public final static int FENRIR = 100, HEL = 101, JORMUNGUND = 102, LUIN = 103, ORMENOS = 104, GULGANNA = 106,
			NARGUND = 107, FAMLICUS = 108, ARK = 109, CONQUISTIS_GUERNICUS = 110, BABEL = 111, MORTIS = 112,
			MAX_MINDSCAPE_NPC = 120;

	public abstract String getTitle();

	public abstract Image getImg();

	public abstract Image acqGetImg();

	public abstract String toString();

	public abstract String acqToString();

	public abstract String getExplanationText();

	public abstract String getImgPathway();
}
